version: '2'
services:
    jsmartbot-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jsmartbot/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jsmartbot
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
